services:
  app:
    build: .
    container_name: derakht-app
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./public/audio:/app/public/audio
      - /app/node_modules
    logging:
      driver: "local"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  audio-storage:
    name: derakht-audio